### ISSUE TITLE
set one single workdir

### ISSUE THREAD

**Issue by shadiakiki1986** [korya/node-git-rest-api#1]
Hi. Thanks for this repository. I tried to run it as exemplified on the readme, but I couldn't figure out how to have one single work directory for all requests, regardless of the cookie contents. Is this possible as it stands now?

I just hard-coded a folder name [here](https://github.com/korya/node-git-rest-api/blob/master/rest-api.js#L78), but I was wondering if there is more legitimate way via the config for example

**Comment by korya** [comment]
Hi. I did not touch this project for years. But as I can understand:
- `workDir` is set from `config.tmpDir` (see https://github.com/korya/node-git-rest-api/blob/master/rest-api.js#L84);
- the value of `config.tmpDir` defaults to `'/tmp/git'` (see https://github.com/korya/node-git-rest-api/blob/master/rest-api.js#L14);
- the best part is that you can override it when you initialize a server instance (see https://github.com/korya/node-git-rest-api/blob/master/server.js#L8).

I hope this helps.

**Comment by shadiakiki1986** [comment]
Thanks korya for taking the time to give me a detailed answer. I had
already tried overwriting the temp dir. My issue is with the work dir that
gets created inside the temp dir. It seems that for each new cookie, a new
work dir gets created, specific to that cookie. I guess I'll just make a
fork and add an override to the work dir from an env variable, similar to
your method to override the temp dir. Then I'll make a PR if you find it ok

**Comment by korya** [comment]
Great! It works for me.
