### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by kasbah** [korya/node-git-rest-api#5]
Hey, this looks interesting! I was wondering what license I can use this under. 

P.S. I started something similar before I found this: [git-clone-server](https://github.com/kasbah/git-clone-server), though it only does clones for now.

**Comment by korya** [comment]
Good question. I have added an MIT license to the repo. As far as I know it is the least restrictive license.

Regarding the project. At a time I just needed something a very simple back-end solution providing HTTP API that is very close to the original git CLI commands. I used it to control a remote git repository from an in-browser IDE, and it worked just fine.

**Comment by kasbah** [comment]
Thanks! @shadiakiki1986 are you happy to license your contributions under the MIT as well?

I am currently considering using this for my site [Kitnic](https://github.com/monostable/kitnic) to manage user submitted projects instead of continuing to expand git-clone-server.

**Comment by shadiakiki1986** [comment]
Sure
